name: Proxy Scraper & Sorter

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  scrape_and_sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks beautifulsoup4 brotli brotlipy

      - name: Prepare README templates
        run: |
          cp README.md.tpl README.md
          cp README_ru.md.tpl README_ru.md

      - name: Run parser
        env:
          PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
        run: |
          python3 proxy_scraper.py

      - name: Update README files
        run: |
          python3 update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.txt README.md README_ru.md
          git commit -m "Update proxy lists and stats: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push

  github_pages:
    needs: scrape_and_sort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for speed tests
        run: |
          python3 -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks

      - name: Run proxy speed tests and update site
        run: |
          # Скрипт speed_test.py должен протестировать все прокси, кроме All.txt,
          # а затем записать результаты в нужный файл (например, в index.html)
          python3 speed_test.py --exclude All.txt
          # Скрипт update_gh_pages.py обновит HTML-страницу (index.html) для GitHub Pages
          python3 update_gh_pages.py

      - name: Deploy updated site to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update GitHub Pages: $(date +'%Y-%m-%d %H:%M')"
          git push origin HEAD:gh-pages
