name: Proxy Scraper & Sorter

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  scrape_and_sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks requests beautifulsoup4

      - name: Run parser
        env:
          PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
        run: |
          python3 proxy_scraper.py

      - name: Update README statistics
        run: |
          python3 update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.txt README.md
          git commit -m "Update proxy list and stats: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
