name: Proxy Scraper & Deploy Pages

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  scrape_and_sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks beautifulsoup4 brotli brotlipy

      - name: Prepare README templates
        run: |
          cp README.md.tpl README.md
          cp README_ru.md.tpl README_ru.md

      - name: Run parser
        env:
          PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
        run: |
          python3 proxy_scraper.py

      - name: Update README files
        run: |
          python3 update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.txt README.md README_ru.md
          git commit -m "Update proxy lists and stats: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push

  github_pages:
    needs: scrape_and_sort
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for speed tests
        run: |
          python3 -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks

      - name: Run proxy speed tests and update site
        run: |
          # Скрипт speed_test.py проводит тестирование скорости для всех файлов,
          # кроме All.txt; затем update_gh_pages.py генерирует новый index.html.
          python3 speed_test.py --exclude All.txt
          python3 update_gh_pages.py

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
