name: Proxy Scraper & Sorter

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  scrape_and_sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Run parser
        env:
          PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
        run: |
          python3 proxy_scraper.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add All.txt HTTP.txt HTTPS.txt Socks4.txt Socks5.txt
          git commit -m "Update proxy list" || echo "No changes to commit"
          git push
